class Backtest_Setting(object):
    def __init__(self,
                 start_date="2018-01-10",
                 end_date="2022-12-31",
                 fiscal_start_year=2007,
                 fiscal_end_year=2022,
                 source="mdna",
                 score="datascore",
                 primaryindex="S&P 500",
                 ExitMode="Rebalance",
                 lookback=60,
                 holdingdays=80,
                 lag=0,
                 up_cutoff=0.5,
                 low_cutoff=0.5,
                 initial_cash=1000000,
                 N_LONGS=10,
                 N_SHORTS=10,
                 DoShort=False,
                 DoLog=False,
                 days_offset=0,
                 short_low_cutoff=0.5,
                 short_up_cutoff=0.5):
        self.start_date = start_date
        self.end_date = end_date
        self.fiscal_start_year = fiscal_start_year
        self.fiscal_end_year = fiscal_end_year
        self.source = source
        self.score = score
        self.primaryindex = primaryindex
        self.ExitMode = ExitMode
        self.lookback = lookback
        self.holdingdays = holdingdays
        self.up_cutoff = up_cutoff
        self.low_cutoff = low_cutoff
        self.initial_cash = initial_cash
        self.N_LONGS = N_LONGS
        self.N_SHORTS = N_SHORTS
        self.DoShort = DoShort
        self.lag = lag
        self.do_log = DoLog
        self.days_offset = days_offset
        self.short_low_cutoff = short_low_cutoff
        self.short_up_cutoff = short_up_cutoff
